name: EXIT-play
on: [workflow_dispatch]


jobs:

  exit_job:
    # Job that is usewd to control what happens in the next job
    name: ðŸŽŒ  Exit-job
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: exit step
        id: check
        run: |
          echo "The next step should not run"
          echo "should_run=false" >> "$GITHUB_OUTPUT"

  main_job:
    needs: exit_job
    if : needs.exit_job.outputs.run == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "This should not run"
