name: EXIT-play
on: [workflow_dispatch]


jobs:
  exit_job:
    name: ğŸŒ  Exit job
    runs-on: ubuntu-latest

    steps:
      - name: exit step
        run: |
          echo "The next step should not run"
          exit 0
      - name: ğŸ© run-commands
        run: |
          echo "The SHELL is `echo $SHELL`"
