name: My WF2
on: [workflow_dispatch]
defaults:
  run:
    shell: bash

jobs:
  first_job:
    name: ğŸŒ  First job
    runs-on: ubuntu-latest

    steps:
      - name: iesire
        run: |
          echo "Dupa stepul asta nu se mai executa nimic"
          # Daca mai jos este exit 1 atunci totul se opreste aici
          exit 0
      - name: ğŸ© run-commands
        run: |
          echo "The SHELL is `echo $SHELL`"
          echo "The used shell is " "${0}"
          echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
          echo "Current branch is ${{ github.ref }}. ğŸ‘½ "
          echo "The current directory is `pwd`."
          echo "My secret is ${{ secrets.MY_SECRET }}. ğŸ˜¶"

      - name: ğŸ© Checkout
        uses: actions/checkout@v6.0.1

      - name: ğŸ© Run tree
        run: |
          tree
          ls -al

  Test:
    runs-on: ubuntu-latest
    name: ğŸŒ  Test
    environment: Test
    needs: first_job

    steps:
      - name: ğŸ©  test commands
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          sec=$(echo "$MY_SECRET" | sed 's/./& /g')
          echo "sec=$sec"
